"""
src/ingestion/data_loader.py
=============================
Loads transaction data from any supported source and normalises it
to the canonical schema used throughout the pipeline:

    sender_account | receiver_account | transaction_amount | timestamp | is_fraud

Supported sources:
  - PaySim CSV  (your existing dataset)
  - AMLSim CSV
  - Synthetic   (generated by data_generator.py)
  - Any CSV that can be column-mapped
"""

import pandas as pd
import numpy as np
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from config.config import *
from src.ingestion.data_generator import generate_synthetic_dataset


# ── Column mapping definitions ────────────────────────────────────────────────
# Keys = canonical name, values = known aliases in raw datasets
COLUMN_ALIASES = {
    "sender_account":    ["nameOrig", "sender", "source_account",
                          "from_account", "sender_account", "orig"],
    "receiver_account":  ["nameDest", "receiver", "dest_account",
                          "to_account", "receiver_account", "dest"],
    "transaction_amount":["amount", "transaction_amount", "tx_amount",
                          "value", "amt"],
    "timestamp":         ["step", "timestamp", "date", "time",
                          "transaction_date", "ts"],
    "is_fraud":          ["isFraud", "is_fraud", "fraud", "label",
                          "isFlaggedFraud"],
}


def _resolve_columns(df: pd.DataFrame) -> dict[str, str]:
    """Return mapping {canonical_name: actual_column_name_in_df}."""
    resolved = {}
    for canon, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in df.columns:
                resolved[canon] = alias
                break
    return resolved


def _normalise(df: pd.DataFrame, col_map: dict[str, str],
               source_name: str) -> pd.DataFrame:
    """Rename columns to canonical names and cast types."""
    out = pd.DataFrame()

    # Required columns
    for req in ["sender_account", "receiver_account", "transaction_amount"]:
        if req not in col_map:
            raise ValueError(f"[{source_name}] Cannot find column for '{req}'. "
                             f"Available: {list(df.columns)}")
        out[req] = df[col_map[req]].astype(str)

    out["transaction_amount"] = pd.to_numeric(
        df[col_map["transaction_amount"]], errors="coerce"
    ).fillna(0).abs()

    # Timestamp — handle both datetime and integer step columns
    if "timestamp" in col_map:
        raw_ts = df[col_map["timestamp"]]
        if pd.api.types.is_numeric_dtype(raw_ts):
            # PaySim 'step' = hours since epoch → convert to datetime
            base = pd.Timestamp("2023-01-01")
            out["timestamp"] = base + pd.to_timedelta(raw_ts, unit="h")
        else:
            out["timestamp"] = pd.to_datetime(raw_ts, errors="coerce")
    else:
        # No time column — generate synthetic monotonic timestamps
        out["timestamp"] = pd.date_range(
            "2023-01-01", periods=len(df), freq="1min"
        )

    # Label — optional
    if "is_fraud" in col_map:
        out["is_fraud"] = pd.to_numeric(
            df[col_map["is_fraud"]], errors="coerce"
        ).fillna(0).astype(int)
    else:
        out["is_fraud"] = 0   # unknown → treat as unlabelled

    return out.dropna(subset=["sender_account", "receiver_account"])


def load_paysim(path=None, sample_n: int = None) -> pd.DataFrame:
    """
    Load PaySim CSV.
    Handles both versions:
      - with  'step' column (original PaySim)
      - without 'step' column (your version)
    """
    path = path or PAYSIM_PATH
    print(f"Loading PaySim from {path}...")
    df = pd.read_csv(path)
    print(f"  Raw rows: {len(df):,}")

    if "type" in df.columns:
        df = df[df["type"].isin(["TRANSFER", "CASH_OUT"])].copy()
        print(f"  Filtered to TRANSFER/CASH_OUT: {len(df):,} rows")
    else:
        df = df.copy()

    col_map = _resolve_columns(df)
    out = _normalise(df, col_map, "PaySim")

    if "type" in df.columns:
        out["type"] = df["type"].astype(str).values
    else:
        out["type"] = "UNKNOWN"

    numeric_cols = [
        "oldbalanceOrg", "newbalanceOrig",
        "oldbalanceDest", "newbalanceDest",
        "step", "isFlaggedFraud",
    ]
    for col in numeric_cols:
        if col in df.columns:
            out[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    out["sender_drained"] = (
        (out.get("newbalanceOrig", 0) <= 1.0) &
        (out.get("oldbalanceOrg", 0) > 0)
    ).astype(int)
    out["dest_no_increase"] = (
        (out.get("newbalanceDest", 0) - out.get("oldbalanceDest", 0)) < 1.0
    ).astype(int)
    out["is_round_amount"] = (
        (out["transaction_amount"] > 0) &
        (np.mod(out["transaction_amount"], TEST_TX_ROUND_MODULO) == 0)
    ).astype(int)

    out["origin_balance_delta"] = (
        out.get("oldbalanceOrg", 0) - out.get("newbalanceOrig", 0)
    )
    out["dest_balance_delta"] = (
        out.get("newbalanceDest", 0) - out.get("oldbalanceDest", 0)
    )
    out["origin_balance_error"] = (
        out["origin_balance_delta"] - out["transaction_amount"]
    ).abs()
    out["dest_balance_error"] = (
        out["dest_balance_delta"] - out["transaction_amount"]
    ).abs()
    out["balance_error_flag"] = (
        (out["origin_balance_error"] > 1.0) |
        (out["dest_balance_error"] > 1.0)
    ).astype(int)
    out["source"] = "paysim"
    out = out.sort_values("timestamp").reset_index(drop=True)

    if sample_n and len(out) > sample_n:
        fraud_df = out[out["is_fraud"] == 1]
        normal_df = out[out["is_fraud"] == 0]
        if len(fraud_df) >= sample_n:
            n_fraud = max(sample_n // 2, 1)
            n_normal = max(sample_n - n_fraud, 1)
            fraud_df = fraud_df.sample(min(n_fraud, len(fraud_df)), random_state=RANDOM_STATE)
            if len(normal_df) > n_normal:
                normal_df = normal_df.sample(n_normal, random_state=RANDOM_STATE)
            print(
                f"  Sample size below fraud count; using {len(fraud_df):,} fraud and "
                f"{len(normal_df):,} normal rows"
            )
        else:
            n_normal = max(sample_n - len(fraud_df), 0)
            if n_normal < len(normal_df):
                normal_df = normal_df.sample(n_normal, random_state=RANDOM_STATE)
        out = (
            pd.concat([fraud_df, normal_df], ignore_index=True)
            .sort_values("timestamp")
            .reset_index(drop=True)
        )
        print(f"  Sampled to {len(out):,} rows (kept all {len(fraud_df):,} fraud rows)")

    save_cols = [
        "sender_account", "receiver_account", "transaction_amount", "timestamp",
        "is_fraud", "type", "oldbalanceOrg", "newbalanceOrig",
        "oldbalanceDest", "newbalanceDest", "sender_drained",
        "dest_no_increase", "is_round_amount", "origin_balance_error",
        "dest_balance_error", "balance_error_flag",
    ]
    canonical_path = DATA_PROCESSED / "paysim_canonical.csv"
    out[[c for c in save_cols if c in out.columns]].to_csv(canonical_path, index=False)
    print(f"  Saved canonical PaySim → {canonical_path}")

    _print_summary(out, "PaySim")
    return out


def load_amlsim(path=None, sample_n: int = None) -> pd.DataFrame:
    """Load AMLSim transaction log."""
    path = path or AMLSIM_PATH
    print(f"Loading AMLSim from {path}...")
    df = pd.read_csv(path)
    col_map = _resolve_columns(df)
    out = _normalise(df, col_map, "AMLSim")
    out = out.sort_values("timestamp").reset_index(drop=True)
    out["source"] = "amlsim"

    if sample_n and len(out) > sample_n:
        out = out.sample(sample_n, random_state=RANDOM_STATE).reset_index(drop=True)

    _print_summary(out, "AMLSim")
    return out


def load_synthetic(path=None, regenerate: bool = False) -> pd.DataFrame:
    """Load or regenerate synthetic dataset."""
    path = path or SYNTHETIC_TX
    if regenerate or not path.exists():
        print("Generating fresh synthetic dataset...")
        return generate_synthetic_dataset(save=True)

    print(f"Loading synthetic dataset from {path}...")
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df["source"] = "synthetic"
    _print_summary(df, "Synthetic")
    return df


def load_csv(path: str, column_map: dict = None) -> pd.DataFrame:
    """
    Generic loader for any CSV with optional manual column mapping.
    column_map: {canonical_name: actual_column_name}
    """
    print(f"Loading CSV from {path}...")
    df = pd.read_csv(path)
    if column_map:
        col_map = column_map
    else:
        col_map = _resolve_columns(df)
    out = _normalise(df, col_map, path)
    out["source"] = "custom"
    _print_summary(out, path)
    return out


def _print_summary(df: pd.DataFrame, name: str):
    """Print a concise data summary."""
    print(f"\n  [{name}] Loaded {len(df):,} transactions")
    print(f"  Unique senders   : {df['sender_account'].nunique():,}")
    print(f"  Unique receivers : {df['receiver_account'].nunique():,}")
    print(f"  Amount range     : {df['transaction_amount'].min():,.2f} – "
          f"{df['transaction_amount'].max():,.2f}")
    print(f"  Date range       : {df['timestamp'].min().date()} → "
          f"{df['timestamp'].max().date()}")
    if df["is_fraud"].sum() > 0:
        print(f"  Fraud rate       : {df['is_fraud'].mean():.4%}")
    else:
        print(f"  Fraud labels     : not available")
    print()
